# Generated by Django 2.2.7 on 2019-11-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('codigo', models.IntegerField()),
                ('fabricacao', models.DateField()),
                ('validade', models.DateField()),
                ('entrada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=150)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.Lote')),
            ],
        ),
    ]
