# Generated by Django 2.2.7 on 2019-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
