# Generated by Django 2.2.7 on 2019-11-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='nome',
            new_name='nome_produto',
        ),
    ]
