# Generated by Django 2.2.7 on 2019-11-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20191122_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='nome',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lotes', to='estoque.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricacao',
            field=models.DateField(default="2019-10-11"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='unidades',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(default="2004-11-12"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='estoque.Tipo'),
            preserve_default=False,
        ),
    ]
