# Generated by Django 2.2.7 on 2019-11-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20191129_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
